theme: jekyll-theme-cayman
title: Reza Nopour
description: Master of Science, Mechanical Engineer
<link rel="shortcut icon" type="image/x-icon" href="web-component-big.png">

email: rnopour@aut.ac.ir
